# Generated by Django 2.0.2 on 2018-02-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180215_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='cv',
            field=models.CharField(default='https://drive.w4pity.fr/drive/CV_PETROCCHI_MELVYN.pdf', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='git',
            field=models.CharField(default='https://bitbucket.org/w4pity/', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com/in/melvyn-petrocchi/', max_length=64),
            preserve_default=False,
        ),
    ]
