# Generated by Django 2.0.2 on 2018-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180215_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='about',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
