# Generated by Django 2.0.2 on 2018-02-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='pseudo',
            field=models.CharField(default='W4pity', max_length=64),
            preserve_default=False,
        ),
    ]
